---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: discovery-service
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./discovery-service/kustomize/overlays/local
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: cobol-to-microservices
  targetNamespace: services
  timeout: 3m0s
  wait: true
