---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize/base
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: cobol-to-microservices
  targetNamespace: monitoring
  timeout: 3m0s
  wait: true
