apiVersion: v1
kind: Service
metadata:
  name: zos-connect-service
  namespace: services
  labels:
    app: zos-connect-service
spec:
  selector:
    app: zos-connect-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP  # internal-only, exposed via Ingress