apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
  namespace: services
  labels:
    app: configuration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-service
  template:
    metadata:
      labels:
        app: configuration-service
    spec:
      containers:
        - name: configuration-service
          image: agilesolutions/configuration-service:1.0.1
          ports:
            - containerPort: 8091