apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: services
  labels:
    app: configuration-service
spec:
  selector:
    app: configuration-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
  type: ClusterIP  # internal-only, exposed via Ingress