apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: services
  labels:
    app: authorization-service
spec:
  selector:
    app: authorization-service
  ports:
    - name: http
      port: 8092
      targetPort: 8092
  type: ClusterIP  # internal-only, exposed via Ingress